### ISSUE TITLE
Fails to load with Next JS

### ISSUE THREAD

**Issue by momakes** [FormidableLabs/urql-devtools#67] opened 2019-09-21 07:33 UTC
When clicking on "URQL" in dev tools I receive these errors (These are emitted in the chrome, not the console):
```
"TypeError: Cannot read property 'map' of undefined", source: chrome-extension://urql-devtools/panel.js (45493)

"Uncaught TypeError: Cannot read property 'map' of undefined", source: chrome-extension://urql-devtools/panel.js (45543)

"Uncaught (in promise) TypeError: Failed to fetch", source: chrome-extension://urql-devtools/panel.js (46210)
```

![image](https://user-images.githubusercontent.com/55196141/65370072-2f511d80-dc6a-11e9-8f2d-dff842bea1bb.png)

```
import { createClient, dedupExchange, fetchExchange } from 'urql'
import { devtoolsExchange } from '@urql/devtools'
import { cacheExchange } from '@urql/exchange-graphcache'

const IS_PROD = process.env.NODE_ENV === 'production'
const IS_BROWSER = typeof window !== 'undefined'

import 'isomorphic-fetch'

export const createUrqlClient = () => {
  const exchanges = [dedupExchange, cacheExchange(), fetchExchange]

  if (IS_BROWSER) {
    exchanges.push(devtoolsExchange)
  }

  return createClient({
    url: IS_PROD ? `https://x.there.team/api` : `http://localhost:7001/api`,
    exchanges,
  })
}
```

Debugging aid:
- React dev tools works fine.
- `window.__urql__.url` is set correctly in console.
- Introspection is enabled, I checked with Apollo Server's Playground.

**Comment by lukasluecke** [comment] 2019-09-23 10:25
I have the same problem, was just about to create an issue when I saw this one.

**Comment by JoviDeCroock** [comment] 2019-09-23 10:44
Gave this a look and it seems that event.panels is undefined. This is hard for me to grasp since we seem to always return one https://github.com/FormidableLabs/urql-devtools/blob/ff617d93458afc74dce31ab1e249680ecb88efde/src/panel/context/Events.tsx#L204 we could guard it but this seems like a deeper issue, I'll try to setup a minimal reproduction.

**Comment by momakes** [comment] 2019-09-23 10:46
@JoviDeCroock Thank you. FWIW, I got the error by the most minimal example with just one query `{ dummy: String }` and no Mutation.

**Comment by JoviDeCroock** [comment] 2019-09-23 10:56
I've tried this and it seems that the devtools (and exchange) need a new release, when using the one from the chrome store I see your error. When using my local version it just works (hence why I was getting confused)

**Comment by lukasluecke** [comment] 2019-09-23 11:00
@JoviDeCroock Could you also release a new version of the exchange? My fix for the SSR would probably be good to have for NextJS usage as well 🙂

**Comment by lukasluecke** [comment] 2019-09-23 11:01
@JoviDeCroock Thanks for the quick reply, looking forward to the new releases 🙂 since I'm trying to debug some issues with the graphcache right now it would really come in handy to have the DevTools 😁

**Comment by momakes** [comment] 2019-09-23 11:35
@lukasluecke Thank you too for debugging graphcache! I'm noticing an issue with `catch-and-network` not caching, I'm also needed the devtool for this :)

**Comment by lukasluecke** [comment] 2019-09-23 11:39
@momakes Might be related to my issue then - it also involves some unexpected cache misses 😅 not really a huge issue, since it will just load the data in that case - but I'll try to figure it out anyway 🙂

**Comment by JoviDeCroock** [comment] 2019-09-23 12:07
@lukasluecke @momakes if you want we can talk about the (maybe) bug on spectrum. If it helps you can use the following template to try and minimally reproduce the issue: https://codesandbox.io/s/urql-issue-template-client-iui0o

If you can describe the issue I can also give it a shot. Thanks for the issue reporting, helps us ensure to give you all a good experience!

**Comment by lukasluecke** [comment] 2019-09-23 12:33
@JoviDeCroock I will create an issue and / or reproduction once I know it's actually an issue with the cache - which would probably be easier to find out, if I can use the dev tools 😉 It might just as well be a problem with my project 🙈

**Comment by JoviDeCroock** [comment] 2019-09-23 12:38
For the time being you can use the `network` tab it should show similar things to the devtools but less structured and without the meta.

Pinging the needed people for that publish in the meantime

**Comment by lukasluecke** [comment] 2019-09-23 12:40
@JoviDeCroock The problem with the `network` tab is, that the data returned is correct - it's jsut that there should not be a request at all. Sadly the reproduction template (or in this case, the linked GraphQL server) only has list queries, no item queries. I'll create an issue describing my general issue in the graphcache repository meanwhile 🙂

**Comment by BjoernRave** [comment] 2019-10-17 22:26
I think this is fixed now with the newest version. At least it works for me

**Comment by JoviDeCroock** [comment] 2019-10-17 22:26
Thanks for notifying, yes it should be! If anyone else runs into it feel free to ping

**Closed** 2019-10-17 22:26 UTC

**Comment by edw19** [comment] 2021-08-18 01:56
I have this warning in nextjs

DevTools failed to load source map: Could not load content for chrome-extension://mcfphkbpmkbeofnkjehahlmidmceblmm/content_script.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by andyrichardson** [comment] 2021-08-18 09:43
@edw19 this looks to be unrelated - feel free to create a new issue if it's impacting your ability to use devtools :+1:
